spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:swp;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  messages:
    basename: i18n/messages
  jpa:
    properties:
      hibernate.jdbc.time_zone: Asia/Ho_Chi_Minh
    show-sql: true
server:
  servlet:
    session:
      persistent: false